services:

  reppo-website:
    build:
      dockerfile: Dockerfile.local
    command: pnpm run local-serve
    container_name: reppo-website
    networks:
      - reppo
    ports:
      - target: 80
        published: 2001
    volumes:
      - type: bind
        consistency: consistent
        source: .
        target: /src
      - type: bind
        consistency: consistent
        source: ../../scripts/common
        target: /src/scripts/common
    working_dir: /src
