import {
	LucideAlertTriangle,
	LucideBeaker,
	LucideBoxes,
	LucideBrain,
	LucideBriefcase,
	LucideCalendar,
	LucideCalendars,
	LucideChevronDown,
	LucideCircleCheck,
	LucideClipboard,
	LucideClipboardCopy,
	LucideClipboardList,
	LucideClipboardPaste,
	LucideCoins,
	LucideDoorClosed,
	LucideDot,
	LucideEdit,
	LucideFileQuestion,
	LucideHistory,
	LucideHome,
	LucideLogs,
	LucidePlug,
	LucideRefreshCcw,
	LucideRefreshCw,
	LucideSettings,
	LucideShield,
	LucideSparkle,
	LucideSquareArrowRightEnter,
	LucideTestTube,
	LucideTrash,
	LucideUser,
	LucideUsers,
	LucideX,
} from "lucide-react";

export const ThemeIcon = {
	Common_AI: LucideSparkle,
	Common_Clear: LucideX,
	Common_Copy: LucideClipboardCopy,
	Common_Dropdown: LucideChevronDown,
	Common_Edit: LucideEdit,
	Common_Delete: LucideTrash,
	Common_Error: LucideAlertTriangle,
	Common_Home: LucideHome,
	Common_NotFound: LucideFileQuestion,
	Common_Paste: LucideClipboardPaste,
	Common_Reason: LucideBrain,
	Common_Refresh: LucideRefreshCcw,
	Common_Reload: LucideRefreshCw,
	Common_Success: LucideCircleCheck,
	Common_View: LucideSquareArrowRightEnter,


	Audit: LucideHistory,

	Cron: LucideCalendar,
	Crons: LucideCalendars,

	Job: LucideClipboard,
	Jobs: LucideClipboardList,

	Root_Gateway: LucideDoorClosed,
	Root_Gateway_Credits: LucideCoins,
	Root_Gateway_Models: LucideLogs,
	Root_Groups: LucideBriefcase,
	Root_Home: LucideShield,
	Root_Settings: LucideSettings,
	Root_Users: LucideUsers,

	SimulationSpec: LucideTestTube,
	SimulationRun: LucideBeaker,

	Socket: LucidePlug,

	Workspace: LucideBriefcase,
	Workspaces: LucideBoxes,
	Workspace_Home: LucideHome,
	Workspace_User: LucideUser,
	Workspace_Users: LucideUsers,
	Workspace_Settings: LucideSettings,

	Unknown: LucideDot,
};
