---
config:
  theme: neutral
---
flowchart TB
    classDef titleStyle fill: #FFF, stroke: #000, color: #000, font-size: 1em, font-weight: bold;
    classDef noteStyle fill: #FFA, stroke: #A00, color: #000, font-size: .9em;

    title["Flow: Socket Queue, v2026818.01 © Cheese Industries Inc."]:::titleStyle
    title~~~diagram
    subgraph diagram ["_"]
        direction TB

        subgraph dashboard ["`**reppo-dashboard**`"]
           subgraph cronScreen ["Crons (screen)"]
                subgraph dashboardSend ["Sends"]
                    subgraph socketWatch1 ["`**socket-watch** (1)`"]
                        socketWatch1Note["`The **socket-watch** message is sent when entering/leaving the **Crons** screen with appropriate data, ie: **cron-list** type, **isWatch** flag, arbitrary component-specific **key**, and **filter** object.`"]:::noteStyle
                    end
                end
                subgraph dashboardReceive ["Receives"]
                    subgraph cronUpdateList3 ["`**cron-update-list** (3)`"]
                        cronUpdateList3Note["`Receiving **cron-update-list** message triggers data refresh.`"]:::noteStyle
                    end
                end
           end
        end
        
        subgraph reppoApi ["reppo-api"]
            subgraph cron ["`**cron** (module)`"]
                subgraph cronUpdate1 ["`**cron-update** (1)`"]
                    cronUpdate1Note["`A **cron-update** message is **broadcast** via **global** topic.`"]:::noteStyle
                end
            end
            subgraph socketPool ["SocketPool"]
                socketPoolNote["`Pool tracks active sockets and used to distribute messages.`"]:::noteStyle
                socketPoolNote ~~~ socket
                subgraph socket ["Socket"]
                    socketNote["`An individual socket is open for each **reppo-dashboard** instance via **GET api/socket** route.`"]:::noteStyle
                    socketNote ~~~ socketListen
                    subgraph socketListen ["Listen"]
                        socketListenNotes["`Listen to incoming messages.`"]:::noteStyle
                        socketListenNotes ~~~ socketWatch2
                        subgraph socketWatch2 ["`**socket-watch** (2)`"]
                        end
                    end
                    subgraph socketUser ["User"]
                        subgraph socketPermitter ["Permitter"]
                        end
                    end
                    subgraph socketWatchers ["Watchers"]
                        socketWatchersNote["`Tracks **watch** listeners by their **key** to cross-check **filter** object, if permitted.`"]:::noteStyle
                        socketWatchersNote ~~~ socketWatch3
                        subgraph socketWatch3 ["`**socket-watch** (3)`"]
                        end
                    end
                    subgraph socketSend ["Send"]
                        socketSendNote["`Sends messages to socket.`"]:::noteStyle
%%                        socketSendNote ~~~ cronUpdateList2
                        subgraph cronUpdateList2 ["`**cron-update-list** (2)`"]
                            cronUpdateList2Note["`Decision to send message is a function of watch filters and user permissions.`"]:::noteStyle
                        end
                    end
                end
                subgraph cronUpdateList1 ["`**cron-update-list** (1)`"]
                    cronUpdateList1Note["`Message received by pool and distributed to every socket, as needed.`"]:::noteStyle
                end
            end
            subgraph queue ["`**queue** (module)`"]
                subgraph queuePublisher ["`Publisher`"]
                    subgraph cronUpdate2 ["`**cron-update** (2)`"]
                    end
                end
                subgraph queueSubscriber ["`Subscriber`"]
                    subgraph cronUpdate3 ["`**cron-update** (3)`"]
                        cronUpdate3Note["`The queue **cron-update** triggers socket to send **cron-update-list** (and **cron-update-single**) messages.`"]:::noteStyle
                    end
                end
            end
        end

        subgraph pubsub ["Google PubSub"]
            subgraph globalTopic ["`**global** (topic)`"]
                globalTopicNote["`The **global** topic is used to broadcast to all pods/containers.`"]:::noteStyle
            end
        end

        socketWatch1 --->|Send| socketWatch2
        socketWatch2 --->|Track| socketWatch3
        socketWatch2 -...->|Filter| socketPermitter
        cronUpdate1 -->|Publish| cronUpdate2
        cronUpdate2 -->|Publish| globalTopic
        cronUpdate3 -->|Receives| globalTopic
        cronUpdateList1 ---->|Generated by| cronUpdate3
        cronUpdateList2 --------->|Receives| cronUpdateList1
        cronUpdateList2 -..->|Filter| socketWatch3
        cronUpdateList2 -..->|Filter| socketPermitter
        cronUpdateList3 --->|Receives| cronUpdateList2

    end
