include='/var/lib/postgresql/data/postgresql.conf'

# This little guy discourages Seq Scan in favor of Index Scan, if available, which helps with testing.
# https://www.postgresql.org/docs/13/indexes-examine.html
# https://www.postgresql.org/docs/13/runtime-config-query.html
enable_seqscan = off

# Remove [public] schema from search path to force explicit schema usage.
# https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATTERNS
# search_path = ''
